services:
  # The Game Server (WebSocket)
  - type: web
    name: hari-deal-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: server
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
